version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2023.02
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    steps:
      - checkout
      - run:
          name: Set Java version to 11
          command: java -version
      - run: echo "Building the app"
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y lib32stdc++6 lib32z1
            echo y | sdkmanager "ndk-bundle" "cmake;3.10.2.4988404"
      - run:
          name: Grant execute permissions to gradlew
          command: chmod +x ./gradlew
      - run:
          name: Build the APK
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/
          destination: outputs
      - store_test_results:
          path: app/build/test-results/
  test:
    working_directory: ~/code
    docker:
      - image: cimg/android:2023.02
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    steps:
      - checkout
      - run:
          name: Set Java version to 11
          command: java -version
      - run: echo "Running tests"
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y lib32stdc++6 lib32z1
            echo y | sdkmanager "ndk-bundle" "cmake;3.10.2.4988404"
      - run:
          name: Grant execute permissions to gradlew
          command: chmod +x ./gradlew
      - run:
          name: Build the APK and run unit tests
          command: ./gradlew clean assembleDebug test
      - store_test_results:
          path: app/build/test-results/
      - store_artifacts:
          path: app/build/outputs/
          destination: outputs
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build